#!/bin/sh -e
MYDIR=`dirname $0`

MODULES="$(cat $MYDIR/yast-svn-git-diff.list)"

BRANCHES="master
openSUSE-12_1
openSUSE-11_4
Code-11-SP2
Code-11-SP1
SLE-10-SP4
SLE-10-SP3"

#SVNROOT=https://svn.opensuse.org/svn/yast
SVNROOT=file:///home/mvidner/2/yast2git/yast-svn
GITROOT=git://github.com/yast/yast-%s.git

GITCACHE=/var/tmp/github-yast
mkdir -p $GITCACHE

for MODULE in $MODULES; do
    REMOTE=`printf $GITROOT $MODULE`
    echo $REMOTE

    # cannot get github to archive. clone first, shallow is enough
    pushd $GITCACHE >/dev/null
    if [ -d $MODULE/.git -o -f $MODULE/HEAD ]; then
        (cd $MODULE; git fetch)
    else
        git clone --mirror $REMOTE $MODULE
    fi
    GITREPO=file://`pwd`/$MODULE
    popd >/dev/null

    for BRANCH in $BRANCHES; do

        case $BRANCH in
            master)
                SVNBRANCH=trunk ;;
            openSUSE-12_1)
                SVNBRANCH=branches/SuSE-Linux-12_1-Branch ;;
            openSUSE-11_4)
                SVNBRANCH=branches/SuSE-Linux-11_4-Branch ;;
            Code-11-SP2|Code-11-SP1|SLE-10-SP4|SLE-10-SP3)
                SVNBRANCH=branches/SuSE-$BRANCH-Branch ;;
        esac

        SVNREPO=$SVNROOT/${SVNBRANCH?}/$MODULE
        if ! svn info $SVNREPO > /dev/null; then
            echo "$MODULE does not exist in $BRANCH, skipping"
            continue
        fi

        DIFF=$MODULE-$BRANCH.diff
        $MYDIR/yast-svn-git-diff $SVNREPO $GITREPO $BRANCH > $DIFF
        diffstat $DIFF
    done

    rm -rf $DIR
done
